name: Deploy

on:
  push:
    branches: 
      - main
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Create Zipped Package
        run: zip -r Chorus.zip . -x "*.git*" "*.md"
        
      - name: Upload & Publish
        uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          file-path: Chorus.zip
          client-id: ${{ secrets.CLIENT_ID }}
          extension-id: ${{ secrets.EXTENSION_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
