name: Sync
on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
  
jobs:
  nightly-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Nightly Merge
      uses: robotology/gh-action-nightly-merge@v1.4.0
      with:
        allow_ff: true
        ff_only: true
        stable_branch: 'develop'
        development_branch: 'main'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
